# Copyright 2017, 2019, Oracle Corporation and/or affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl

#cloud-config
package_upgrade: ${bastion_package_upgrade}
timezone: ${timezone}
write_files:
# setup script
  - path: "/root/bastion/bastion.sh"
    permissions: "0700"
    encoding: "gzip+base64"
    content: |
      ${bastion_sh_content}
runcmd:
 - echo "Configuring bastion..." | tee /root/bastion/bastion.txt
 - bash /root/bastion/bastion.sh
 - touch /home/opc/bastion.finish